- name: Set up networking
  hosts: localhost
  gather_facts: False
  vars:
    haproxy_backend_servers:
      - {name: target2, ip: 192.168.22.152}
      - {name: target3, ip: 192.168.22.148}
  tasks:
    - name: install haproxy firewalld
      yum:
        name: haproxy

    - name: Update HAProxy config
      template:
        src: templates/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        backup: yes
      become: yes

    - name: enable haproxy service
      service:
        name: haproxy
        state: started
        enabled: yes
    -
      name: open Firewalld for http
      firewalld:
        service: http
        zone: public
        immediate: yes
        permanent: yes
        state: enabled
      become: yes

    - name: Send notification email
      mail:
        host: smtp.gmail.com
        port: 465
        username: mmumshad@gmail.com
        password: "{{ g_password }}"
        to: Mumshad Mannambeth <mmumshad@gmail.com>
        subject: Ansible-report
        body: 'Go to http://{{ lb_result.external_ip }} to access your web application.'