---
# tasks file for db_server
-
  name: install mysql database
  yum:
    name: ['mariadb-server']
    state: installed
  become: yes
-
  name: start mysql server
  service:
    name: mariadb
    state: started
    enabled: yes
  become: yes
-
  name: Create Application database
  mysql_db:
    name: "{{ db_name }}"
  become: yes
-
  name: Create MySQL-User
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present
    host: '%'
  become: yes
-
  name: enable mysql-port in firewall
  firewalld:
    service: mysql
    permanent: yes
    immediate: yes
    state: enabled
  become: yes
