---
# tasks file for http_server
    -
      name: Install HTTP-Server dependency
      yum:
        name: [httpd, php, php-mysqlnd, mariadb]
        state: present
      become: yes
    -
      name: checkout sources
      git:
        repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
        dest: /var/www/html/
        force: yes
      become: yes
    -
      name: init database
      mysql_db:
        login_host: "{{ db_host }}"
        login_port: "{{ db_port | default(3306) }}"
        login_password: "{{ db_password }}"
        login_user: "{{ db_user }}"
        name: "{{ db_name }}"
        state: import
        target: /var/www/html/assets/db-load-script.sql
      ignore_errors: True
    -
      name: remove .git folder
      command: rm -rf /var/www/html/.git
      become: yes
    -
      name: change db-host in connection-config
      replace:
        regexp: "{{ item.patterns }}"
        replace: "{{ item.replacement }}"
        path: /var/www/html/index.php
      become: yes
      loop:
        - patterns: "172.20.1.101"
          replacement: "{{ db_host }}"
        - patterns: "ecomuser"
          replacement: "{{ db_user }}"
        - patterns: "ecompassword"
          replacement: "{{ db_password }}"
        - patterns: "ecomdb"
          replacement: "{{ db_name }}"
    -
      name: change index-file-extension from html to php
      replace:
        patterns: index.html
        replace: index.php
        path: /etc/httpd/conf/httpd.conf
      become: yes
    -
      name: open Firewalld for http
      firewalld:
        service: http
        zone: public
        permanent: yes
        state: enabled
      become: yes
